### ISSUE TITLE
2019-10-26-action3: find reference to file extensions for profiles re annotation (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#123] opened 2019-10-25 16:55 UTC
find reference to file extensions for profiles re annotation (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-25-json-ld#action3))

Cc: @azaroth42

**Comment by azaroth42** [comment] 2019-10-25 20:54
It is not minuted from the Annotation WG minutes :(

@bigbluehat do you have a recollection of this?

My recollection is as follows:
* We discussed with shepazu and danbri at the Sapporo TPAC, probably as a hallway conversation on the Thursday. The result was that shepazu especially cared about the file extension (though that never ended up being registered, otherwise we would have an obvious precedent) and less about the media type per se. Others cared about the JSON-LD-ness, and less about the actual "schema", because the context is a better signal of the schema than a media type. Hence the hallway resolution was profile plus file extension. 
* We then checked with Heather Flanagan and Mark Nottingham that they thought it was okay, as they happened to be there (and we know them).

But as it was never minuted, it never happened. I will reach out to Heather and seek guidance.

**Comment by azaroth42** [comment] 2019-10-25 21:02
Ha, found the email, and have asked Heather if I can share it.

My question to her was:

```
If you could find out the possibility of registering a file extension for a new parameter on an existing media type next week, would be fantastic.

The exact details:
Base media type: application/ld+json
Defined by: http://www.w3.org/TR/json-ld/#iana-considerations
Which has a "profile" parameter, that takes a URI to define the schema.

What we would like to do is register a file extension of '.anno' for the combination of:   application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"

It's hard to tell from 6838 whether this is possible or not.
```

And her response (to paraphrase rather than reproduce without permission):

Expert review is sufficient. Then ask the change controller for ld+json if there should be an update to its registration as well.

Given that this WG is the change controller, all that DID needs to do is ask IANA for expert review. We can update the text in 1.1's IANA Considerations section to note that a registered profile URI should allow for a registered file extension.

**Comment by gkellogg** [comment] 2019-10-28 15:08
👎 to registering `application/jsonld`, if there is a way to avoid it. Registering with a profile parameter, or something like `application/anno-ld+json` would seem preferable. What happens if there are sub-profiles of anno, or some other sub-type?

Surely, we can't be the first format to run-into more than one-level of media-type sub-types.

**Comment by iherman** [comment] 2019-10-28 15:33
> Surely, we can't be the first format to run-into more than one-level of media-type sub-types.

Probably not, and there is no register media type on IANA (at least under `application/*`) with two + signed.

**Comment by azaroth42** [comment] 2019-10-28 15:35
And posting the response from IANA verbatim, now with permission:

```
I would suggest that they go ahead and send a modification request to
iana@iana.org.
We will have the designated expert review the request and we will also
confirm with the change controller of application/jl+json [sic] if the spec
should be updated in addition to the online template.

Feel free to pass them my contact information if they have additional
questions.

Michelle
```

Note that we are the change controller (W3C, and its in our spec, so this WG)

I suggest that we explicitly modify the IANA considerations section to mention this possibility in order to prevent future similar questions.

**Comment by TallTed** [comment] 2019-10-28 16:37
@iherman - The ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-26-json-ld#action3)) link at the start of this issue gets a 404.

**Comment by iherman** [comment] 2019-10-29 11:06
@TallTed settled. Thanks.

**Comment by BigBlueHat** [comment] 2019-10-31 20:02
@iherman that link is broken again...404's.

**Comment by iherman** [comment] 2019-11-01 10:28
@BigBlueHat 

I have changed the link in the initial issue comment to https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-25-json-ld#action3. That works. Which link are you looking for?

**Comment by BigBlueHat** [comment] 2019-11-01 16:16
@iherman must have been a different issue. Thanks for the fix!

**Comment by azaroth42** [comment] 2019-11-01 22:29
Action is done. The issue is in -syntax. Closing.

**Closed by azaroth42** 2019-11-01 22:29 UTC
Labels: action
